

<!--<form   method="post">
    <label>transportation type</label>
    <input type="text"  required name="tr_type">
    <br>
    <label>number/name</label> 
    <input type="text" required name="tr_number/name">
    <br>
    <input type="submit" value="Add transportationmean">
        
   
</form>
-->
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>View Transportation</title>

    <!-- Bootstrap Core CSS -->
    <link href="/transportation/public/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/transportation/public/css/sb-admin.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="/transportation/public/css/plugins/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
  <!--  <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">-->

  
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="../user/home">Control Panel</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    
                    <ul class="dropdown-menu message-dropdown">
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-footer">
                            <a href="#">Read All New Messages</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                  
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Smith <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                     
                        <li>
                            <a href=../user/logout"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                        <a href="../user/home"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                    </li>

                 
                  
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#users"><i class="fa fa-fw fa-arrows-v"></i> Users <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="users" class="collapse">
                            <li>
                                <a href="<?php $this->baseUrl()?>../user/listuser">View Users</a>
                            </li>

                           
                        </ul>
                    </li>


                     <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#Stations"><i class="fa fa-fw fa-arrows-v"></i> Stations <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="Stations" class="collapse">

                            <li>
                                <a href="../station/addstation">Add Stations</a>
                            </li>
                            <li>
                                <a href="../station/viewallstation">View Stations</a>
                            </li>

                         
                        </ul>
                    </li>


                     <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#Transportation"><i class="fa fa-fw fa-arrows-v"></i> Transportation <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="Transportation" class="collapse">

                           <li>
                                <a href="addtransortation">Add Transportation</a>
                            </li>
                            <li>
                                <a href="#">View Transportations</a>
                            </li>


                         
                        </ul>
                    </li>


                    
                  
                    
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Transportation Means
                        </h1>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="../user/home">Dashboard</a>
                            </li>

                             <li class="active">
                                <i class="fa fa-edit"></i> Transportation
                            </li>

                        </ol>
                    </div>
                </div>
                <!-- /.row -->

                <div class="row">
                    <div class="col-lg-6">
                         <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>Transportation Id</th>
                                        <th>Transportation Type</th>
                                        <th>Transportation Name/Number</th>
                                        <th colspan="2">Transportation Process</th>
                                    </tr>
                                </thead>
                                <tbody>
                                   <?php

                                if (isset($this->alldataoftransportation)) {
                                   
                            for($i=0;$i<count($this->alldataoftransportation);$i++){
     
           
                                   echo '<tr><td>';
                                   echo $this->alldataoftransportation[$i]['tr_id'];
                                   echo'</td><td>';
                                   echo $this->alldataoftransportation[$i]['tr_type'];
                                   echo'</td>';
                                   echo'</td><td>';
                                   echo $this->alldataoftransportation[$i]['tr_number/name'];
                                   echo'</td>';
                                    echo'</td><td>';
                                    echo '<a href="'.$this->baseUrl().'/transportationmean/deletetransortation/tr_id/'.$this->alldataoftransportation[$i]['tr_id'].'"><img src="/transportation/public/images/delete.png" alt="Edit" height="25" width="25"></a>';
                                    echo'</td>';
                                    echo'</td><td>';
                                    echo '<a href="'.$this->baseUrl().'/transportationmean/edittransortation/tr_id/'.$this->alldataoftransportation[$i]['tr_id'].'"><img src="/transportation/public/images/edit.png" alt="Edit" height="25" width="25"></a>';
                                    echo'</td>';
                                    echo'</tr>';
            
        }
      
        
        
        
    }

?>
                                  
                                </tbody>
                            </table>
                        </div>    
                       

                    </div>
                   
                </div>
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="/transportation/public/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/transportation/public/js/bootstrap.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="/transportation/public/js/plugins/morris/raphael.min.js"></script>
    <script src="/transportation/public/js/plugins/morris/morris.min.js"></script>
    <script src="/transportation/public/js/plugins/morris/morris-data.js"></script>

</body>

</html>
